<a href="https://colab.research.google.com/github/Aysuliu/ai_foundation/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

In [ ]:
import numpy as np
arr = np.array([1,3,5,7])
print('numpy_array:', arr)

arr.shape

numpy_array: [1 3 5 7]


(4,)

In [ ]:
arr2=np.array([[1,3,5,7],[4,6,8,9]])
print('numpy_array2:', arr2)
arr2.shape

numpy_array2: [[1 3 5 7]
 [4 6 8 9]]


(2, 4)

In [ ]:
#dtype()
a = np.array([1,2,3])
print(a.dtype)

int64


In [ ]:
#reshape()
a = np.array([1,2,3,4,5,6])
b = a.reshape(2,3)
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
#astype()
a = np.array([1,2,3])
b = a.astype(float)
print(b)

[1. 2. 3.]


In [ ]:
#np.zeros(), np.ones() => dummy data
a = np.zeros((2,3))
b = np.ones((2,3))
print(a)
print(b)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#ndim
a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6]])
print(a.ndim)
print(b.ndim)

1
2


In [ ]:
#arange()
a = np.arange(1,6)
print(a)

[1 2 3 4 5]


In [ ]:
#sum(), mean(), max(), min()
a = np.array([1,2,3,4,5])
print(a.sum())
print(a.mean())
print(a.max())
print(a.min())

15
3.0
5
1


In [ ]:
#flatten()
a = np.array([[1,2],[3,4]])
print(a.flatten())

[1 2 3 4]


In [ ]:
# T ( Transpose)
a = np.array([[1,2],[3,4]])
print(a.T)

[[1 3]
 [2 4]]


In [ ]:
# dot() @
a = np.array([[1,2],[3,4]])
b = np.array([[2,0],[1,2]])
print(a.dot(b))
#print(a@b)

[[ 4  4]
 [10  8]]


In [ ]:
#random.rand() => 0.0 and 1.0 / 0.0 included but 1 excluded
a = np.random.rand(2,3)
print(a)

[[0.18869839 0.77660676 0.03208004]
 [0.17259461 0.75802054 0.33199144]]
